language: java
sudo: false

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

# Undo _JAVA_OPTIONS environment variable (https://github.com/travis-ci/travis-ci/issues/8408)
before_script:
  - _JAVA_OPTIONS=

script: "./gradle/buildViaTravis.sh"

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e0f9bf58447bda85e45c
    on_success: always
    on_failure: always
    on_start: never
